### ISSUE TITLE
please use human readable time in logs instead of unix timestamp

### ISSUE THREAD

**Issue by monotek** [kiwigrid/gcp-serviceaccount-controller#6]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feturerequest

**Version of Kubernetes**:
1.14

**What happened**:
log timestamap is unixtimesatmp

**What you expected to happen**:
log in human readable date format

**How to reproduce it** (as minimally and precisely as possible):
kubectl get logs

**Anything else we need to know**:

**Comment by monotek** [comment]
not stale...

**Comment by monotek** [comment]
Not stale

**Comment by rpahli** [comment]
fixed with #7
